branches:
  only:
  - master
  - "/^release.*$/"
env:
  global:
  - GPG_KEY_LOCATION=".travis/secret.gpg"
  - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"
  - secure: iErEEn7Oz6hDCUtaB/pzlM0hz/uSbh4tNLN+mySNpIne7R3sq9kbjvCsAPxGh4Dh+vZUj2cBZxPDmF4kGCukJqD1toO1Yljl790g+he5W0H2BF2CQuGfHrde+KoCb4DoAkgCPEvLXhFTQraGHrwMalXLJ9K6nfWXw06gNrRW1hKRKcFkb2UCV1ucAtBPbDFJjM+Kd9IcZMvqKmw4+awlORJfYIj0vbiTwi7Eot5P4u9gQG05Lak84NWZMxjdvPiSShg5+XKzS/hrLW+PNswiVpfqZiQzrecOzHBWSbK2UJeEey8fzOPxKTNGP3yg39uu2V/+AinjesSpjvbPufgCLTsnRp6gy9XXQr9brFuZCHz903evRERTM1ia33XbC2yl6cbAOdANTDbLH/XQO/4oyD9eKFw4drYwcNcuxCiw6VfE5YQRHrPDn8Y/AloIJ7ZEAVrW5D7YLU4sqIqk0zDrgtUXslkbfjGltfLxWEKGqHP+Tj1PbTqyYLIhozytH03F1eG+FJm1Z1fAk+LON3XCxXKYguXGqlqWuHX7J12hXywIyMaz7PTDbOkmwRw5tMlfMt9JI/2i+Y9iRu5HgwnVdvXBRG6CJPMemrjd6bIa77Z1Ca/V0hfnR5MJ+wHlFXdHoFatiSkeYDXrn0j8wohpe8nw+kxJWuLilB5LFHB4iCQ=
  - secure: bnS/sKGDB89nNBL36l3J4siVe6LfvLhyXZZMNRdOmbXis0hfGaU1H1MwNqlJUr5EiE0koydm6LwnuCqan46nB7ZeH91HZETyzHmG1eJ/VkVMKkXxhRcjwn09oqEIhE+VsT7PzAf37wjrjU7N7ZcDf6SM/vlNBhg6FzSZjecLHtmrv17WIMXgzxe/6fCPE3iUZ3zUI5KFm4SCCpyR1HxIHK34xPMUDr9rdUvhdFJISMOFz/vRH8ifI3JVhOb1SOQdil6UEZzsBT+b2cJor8laAamCiGanfsLgJlRsvVNRY9PHhYoPcms6EcHYgQ7Q14Kf+PkA7DXrYujH1yGW/BnHWI59XE+MHtMhxSpF7sUQQsJs3dBjZXHvhNBb9I74BEpqbtAajBSzoH/WgqYk2bq9SH8A8ZZ7vdKozH3pnPFgzKTyuUxotYh0+JphJWtO7vL0yE9E4TvYoHAyAyBjZHXPlDOIcyK6z5MY98PhUiezXErJesQIHE5YwzyI8PIoTPeG52XoKLpwvgwL2fBVuMlZ+KDaEPbVikJVAKSI0xF0yZ2cNgDs6cRw3eKBbbIT0EJbXRefLr359Py/PMulryHMtx9cknnnXT1efwttcKgCURn+WFNtjtkpp9QcFGRWpz06YCmYSppC1mjhW3/aPN3ipVFk/h8h/5MoGCwig0pgtAo=
  - secure: rdcwloEVagAwtEOoSsGemovZ+EeMgeBJF9/wy4l4qfk7Nll1eGASbiwYqBRLWJUOKMyUf828SCpGlvo/T7STVSxnP0up+LGr3w3mibnvaTV5EvWbBElO/PdUMVR751uvpoGJXUarZaLcKcXCVMek3Izkys3aKIEGR5zmDS/8z/25C+Jogr+KBfyR53EC0n3nnf5P1XXLG3zEfCDU2njSI4Yjy4r1jbgHEV6i+SQZarcbuGOQgLVJ6w/VG7OGvyLF2m1c6WGms25HxWdU117GrcommUuuW1uIk/cMN4MWNV859C/xYnroyEf2AD202Q1hhFuqhhOfLBAlq1lP83Cws23Rh9ABeH3grqlvUVu0/7h1jiF8cLTfFfZw/0Uv2UQF2x06lT+TPYau6+3GDbmhmozBskU+QgJE38OpO5IGGGLd1ooNZWLc3gFLLjJgvQUDEAKUoHIt5nCi1djSSWYVMOB7QZqnUr4amqaPyKJwAmeIHCC2Z4BheMQseEceLIAIGC90wiJefIWJX6vQLRQBrSaH/CU1CprJsGCzxdvxQFjc0IEl7xDsgTqz7hTxtU9wqCHUdjVjO+C5DeDr0drHQJHEgbySpMKPe6UNb0RXfJl8lmY8agS6NlsnC73wJ6Iv34nfcxIQoYlDl7t/tyBQ+ytDt+MphebQB5Ukt0I/YFg=
  - secure: PEcIK+34/zf4xksgNWqu+cizB9GIuJHDpewqkuhwzWv590ZGFOAs/HDx5aNJ2F6NxejWw032E6CoAcQujpuEHi9Qsr4xBarD0VV1OaXnysiCBwHYw5KP9Ktwm01iaem26zXp6K9i9LJse+9km5BpiK3uTStLGgbemuLhQykzQZJAjxHPXDpWH5UuIoWgPSDbvTwQl7C1mzK78kQYqvuXRtPDOXp9SpO7XA+k9lwsdAJ6Wdbaouvt2xu5lLP8X18X7V3juRCmNWkaGd4KdmYRRl7DGdMmOFzF6zpfipi9Q95CDaTc6yZX/O84bk6dFm04fThE04UlS3qfDNsd5ymg30U59nxWumWp/DVKbr6YURcrMMrr8iG+vqjmhpy9Gvd1naQxIQ7YnnDr4cRRBtpeQm3cj3uufb1Pj/5mxqG7mQtPjQpSAAiYqAyT9XGAZeM4v0uUjGHoU9vr0Z81uQRzI662Vnlwd5O5Ows5hMjlkV1aqi4dYx2wpY5feI9V0SywqDwcCb7lUgcGfPM0OaJzWyQgeWvYHy1pu/vidpdGWt+NC3PyPgT6nud14ruX/zXx2Cd4ij9WIdZMMdYcdbdn5UfWLsrdINeCgf6x6GZ7gZYzJXocR9ahiWYBQHQPXD0dXEtY4sN3mQaQ9yyB3g1UrM0oeV9chDKZd0PfTOzIpXU=
language: java
jdk:
- oraclejdk11
- openjdk11
script:
- "./gradlew build"
- "./gradlew samples/minimal:bootRun"
before_install:
- openssl aes-256-cbc -K $encrypted_f594690c56da_key -iv $encrypted_f594690c56da_iv
  -in $ENCRYPTED_GPG_KEY_LOCATION -out $GPG_KEY_LOCATION -d
deploy:
  provider: script
  script: "./gradlew uploadArchives -i"
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_JDK_VERSION = openjdk11 && $TRAVIS_PULL_REQUEST = false"
