# only build master & release* branches
branches:
  only:
    - master
    - /^release.*$/

env:
  global:
  - GPG_KEY_LOCATION=".travis/secret.gpg"
  - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"
  - secure: hEnyBbpb+GJQPUG8YgZfzmBKDsmBeuE72FOcH19xf6UtiuwRuEcPbhj4dCoLig1PDS4FFOu8y1uHWJVKlCiEwxiTcih+VyrEBrfvCKBbHMwUttsr5SuFcnnjyzNnmlrcCVTY5QzjgD80A1mV2Vp1xjoZI/csjFMIBbogr6iLQFzKPD3pjBVqrdKJFeXMgniBD+G5Yr0Sk52nnQP4Ao71KzrZyHGZlx5f4JHtXc2p6+n/OHBx7EbyJw+KeYfkS3wIwmcnaubNVC5Y5yOMyeHttdlSviFaSpu8bMWGad4cbq/jQbnZ6jCItSYtI1fxetGMEYDFme2Ho0JfbeIy0LcKEwK7IQ7lcb7X9YIGu1vbjzMuTukNcAOlTKJ8v1VgzgBbKA4Yux5HYkH1ObUEj2bWiOGAPc83JhZYZztglbg4fBVWhFrM9UIzGahFJHPglUnO8qdU13CglC8kre/h5pHvGXPPjIxXZuApxumbG9BeBsvfVQ2yeAITdOnYCtIsNEbwoCxadhMnVMCa0baRRgmt0eBHj64MJL2e/fPEVMxgYjg0q1s1Lcf5UQkgCBWMW7LRiMo1Zvie1BT7DPAS7F1GeLu7YfEXwOX7xearoW32dAeRmohKbXu3DoPwTuKQaXMjeYhDOcrivEYipIw8iDFpBNuW/lo8Ek/tMRjF56e+6kI=
  - secure: wGlyxc0GlLJbTCJVaYnd2uucSewpTNeBWF2OSw8givU2ENf/I9BeEDgSv2IynSd29iBpeyZYNtdwAu3NuRzTQsN9bc2xgVklIoBxood76OWSmlodctODe82OLhoZ3esh3w7vGoXOeQ2htS9RmXvOGEwNi5EsYtg9d7cu/d8YmkuOapbkiLq1a80mHgsJGKsZpeKwFJP8m2OW55147bxqg9oyE490cEHb4cHtrP11Y0LS7Zc0Ye2OR3ZoXQCtPWx70slRS8HHz3DwI/GfskjuIErWv7rqkseTg7Tfc3t1MuhVfxKcIUXlixUAC8pa3EUEoMu4r887Mqq3HXSpRb/HZNlLnIjvLs/L4NZWRDPaKIY86JH20B0VJpy/Edja+Y2eyB/gLiB/o9jM1rQPrnzpERXCnnPDKUXcIGR/+M1ObnGGwPQYU6i9zicuwzjRgQTus88AKMXwhRdqdP4bQWYCM9ClEgUPLuE9ctZkIUZh5/qiZq//TujPoUKHTaUhotDzOt6x+utXXai7zogKCBFupEJhvK5z3LMyaMQBnLODUEJ3NfHB3GNYSDsH/HLTpbrMoDbmMW35WYPq+FrWeZ0m8+igohVmSzTKwn5bCqdPe7LyLI5usJn2+cJAckFWBu1Mt6pv+ii2tuEDK09HaQTM8eABchM4qblI2hDp4ep5l3Y=
  - secure: q3upIuB75/c3NZM74m4BmDvTtFhRHzhno0lQtMD4YLLixzJeJ5AkpYrAlecY2yOTkrgeVxgDSv7S65Z+N60BHo2wxJ6qOtfke+mDArUBHQAHsFD00nsDbYYlwlzr43qRotXYskf0fbLDRKQ32+SGCUpaP21IaltQDymHynaBhyDYhkm5GrKJE3N3zf+fnfxHh5mTtWV8uhmqiM6fjRcltapEl4O7sSqcPhOybQtRjmXPJMWFQLnKP1HiB4+V5l/iz6nIsl344mzv2DXHaGD9zQBx1scxjZfqYsG/z95cWYol/3h3i5kNEtXVLjkSdrojWgHbmwD8EVFVDodB1+w+cavr/JKGYUZfzOrXdKrDYr1/25XBe7UHqiUcPj6fyUpXqlc4FQBmeuTdpURKp718k9a6bd155djhBMpxBJHcV8DQ33fcyUNCgkuHKkn/N2mv2i7TSXuMEtR/FWgJwA3Js4Fok6DZt3XdKyl9a6QmfD5NASlpGAOT2fgtDf5zucBE2I2m/EZ5JO6/Hm/C9wGGq+wv8EiyC0dmvornIbSMaTnWL/yz8OAk33RHmzWzZIy5oneORxgavsPpk1FZ4uu+nc3fkVAAEYVDK8Cve7X+S266JYmoRRv0ZrBvRvDicNVxRkEZs00JUr7iYNxFeuopfZZfuksM38O1IAqpjhcLrac=
  - secure: J8nDxnqM0gqip1cIlv/zVfB25TiKYt9fRTYkZxf8tazGAB+nuGLQBdEw0anJGCAlmGNvmVRoeW6//xzDIa/Tli5VIeqqyyb3JKQHgtrscrLU3pqu14XDMpvkB1K5koGoRRhXg8JAcgU2Soo6G66qD9IsqYCtAiXMWhiVEWeOH2/s6uC7M0BirE8lw1uNHUW8Jy/dUTqdRDc1DkcxAdyYW50mNnpXYivky8EpVqbg3sTXH4CAHMdgnyUBv3v/uDNPaFm70J7Tf5MGIF0h/VrEBaeOlCT02IUTjkB0SAiV3JeYbRgkdnkaEN4Hw4kdzynp7oUzcOpf9UC5npbt2WtPWpwfYTP2KkiS/eYbMKFzVYvlVGBN3qGAfHnPd2n1PBKaYDvDYHGzq43uD06evcSDL3fgcSyM6NePCZHwIulGp7tnwZJjCaY8khRrICVvbjEhRb9TIiZcQ20UJdCSegTr4vJAI2nnmA4B+t5yMEHlldvXRtmbYN/75skXOLgYrxRQtj7p68ZAq2OmRrqNux+kmkLFWN8a0tQvf0BOtOuwW0eLC8Fm6X+b4L3Wi2UK/5B3i8CJuwk/OrSwjitN/OuLV8vtr0CzwzpssrKKW75MQYgOyfWTGSYKNnf0uAVZpy6Rl+s1ooH/4kM8HuYJ6EyuU5fbQP7sIeat9F6vs6SG9zI=
language: java
jdk:
- oraclejdk11
- openjdk11
script:
- "./gradlew build"
- "./gradlew samples/minimal:bootRun"
before_install:
- openssl aes-256-cbc -K $encrypted_f594690c56da_key -iv $encrypted_f594690c56da_iv
  -in $ENCRYPTED_GPG_KEY_LOCATION -out $GPG_KEY_LOCATION -d


# deploy master to maven central snapshot
deploy:
  provider: script
  script: "./gradlew build uploadArchives"
  on:
    branch: master
    condition: $TRAVIS_JDK_VERSION = openjdk11 && $TRAVIS_PULL_REQUEST = false
